commenting out the check-for-failures job

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -639,61 +639,61 @@ jobs:
           if-no-files-found: error
 
 
-  check-failures:
-    name: Check for failures
-    #if: always()
-    if: false
-    runs-on: ubuntu-20.04
-    needs:
-      - cloc
-      - setup
-      - cli
-      - windows-gui
-      - linux
-      - macos
-    steps:
-      - name: Check if any job failed
-        if: ${{ (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/rc') }}
-        env:
-          CLOC_STATUS: ${{ needs.cloc.result }}
-          SETUP_STATUS: ${{ needs.setup.result }}
-          CLI_STATUS: ${{ needs.cli.result }}
-          WINDOWS_GUI_STATUS: ${{ needs.windows-gui.result }}
-          LINUX_STATUS: ${{ needs.linux.result }}
-          MACOS_STATUS: ${{ needs.macos.result }}
-        run: |
-          if [ "$CLOC_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$SETUP_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$CLI_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$WINDOWS_GUI_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$LINUX_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$MACOS_STATUS" = "failure" ]; then
-              exit 1
-          fi
+      #check-failures:
+      #  name: Check for failures
+      #  #if: always()
+      #  if: false
+      #  runs-on: ubuntu-20.04
+      #  needs:
+      #    - cloc
+      #    - setup
+      #    - cli
+      #    - windows-gui
+      #    - linux
+      #    - macos
+      #  steps:
+      #    - name: Check if any job failed
+      #      if: ${{ (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/rc') }}
+      #      env:
+      #        CLOC_STATUS: ${{ needs.cloc.result }}
+      #        SETUP_STATUS: ${{ needs.setup.result }}
+      #        CLI_STATUS: ${{ needs.cli.result }}
+      #        WINDOWS_GUI_STATUS: ${{ needs.windows-gui.result }}
+      #        LINUX_STATUS: ${{ needs.linux.result }}
+      #        MACOS_STATUS: ${{ needs.macos.result }}
+      #      run: |
+      #        if [ "$CLOC_STATUS" = "failure" ]; then
+      #            exit 1
+      #        elif [ "$SETUP_STATUS" = "failure" ]; then
+      #            exit 1
+      #        elif [ "$CLI_STATUS" = "failure" ]; then
+      #            exit 1
+      #        elif [ "$WINDOWS_GUI_STATUS" = "failure" ]; then
+      #            exit 1
+      #        elif [ "$LINUX_STATUS" = "failure" ]; then
+      #            exit 1
+      #        elif [ "$MACOS_STATUS" = "failure" ]; then
+      #            exit 1
+      #        fi
 
-      - name: Login to Azure - Prod Subscription
-        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
-        if: failure()
-        with:
-          creds: ${{ secrets.AZURE_PROD_KV_CREDENTIALS }}
+      #    - name: Login to Azure - Prod Subscription
+      #      uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
+      #      if: failure()
+      #      with:
+      #        creds: ${{ secrets.AZURE_PROD_KV_CREDENTIALS }}
 
-      - name: Retrieve secrets
-        id: retrieve-secrets
-        uses: Azure/get-keyvault-secrets@80ccd3fafe5662407cc2e55f202ee34bfff8c403
-        if: failure()
-        with:
-          keyvault: "bitwarden-prod-kv"
-          secrets: "devops-alerts-slack-webhook-url"
+      #    - name: Retrieve secrets
+      #      id: retrieve-secrets
+      #      uses: Azure/get-keyvault-secrets@80ccd3fafe5662407cc2e55f202ee34bfff8c403
+      #      if: failure()
+      #      with:
+      #        keyvault: "bitwarden-prod-kv"
+      #        secrets: "devops-alerts-slack-webhook-url"
 
-      - name: Notify Slack on failure
-        uses: act10ns/slack@e4e71685b9b239384b0f676a63c32367f59c2522  # v1.2.2
-        if: failure()
-        env:
-          SLACK_WEBHOOK_URL: ${{ steps.retrieve-secrets.outputs.devops-alerts-slack-webhook-url }}
-        with:
-          status: ${{ job.status }}
+      #    - name: Notify Slack on failure
+      #      uses: act10ns/slack@e4e71685b9b239384b0f676a63c32367f59c2522  # v1.2.2
+      #      if: failure()
+      #      env:
+      #        SLACK_WEBHOOK_URL: ${{ steps.retrieve-secrets.outputs.devops-alerts-slack-webhook-url }}
+      #      with:
+      #        status: ${{ job.status }}
