add arm builds for apple silicon

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -182,6 +182,69 @@ jobs:
           if-no-files-found: error
 
 
+  macos-arm64-cli:
+    name: Build Mac ARM64 CLI
+    runs-on: macos-15
+    needs: setup
+    permissions:
+      contents: read
+    env:
+      _PACKAGE_VERSION: ${{ needs.setup.outputs.package_version }}
+      _NODE_VERSION: ${{ needs.setup.outputs.node_version }}
+      HUSKY: 0
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
+          persist-credentials: false
+
+      - name: Setup Node Environment
+        uses: ./.github/actions/setup-node-env
+        with:
+          node-version: ${{ env._NODE_VERSION }}
+          platform: macOS
+
+      - name: Set up Rust
+        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
+        with:
+          targets: aarch64-apple-darwin
+
+      - name: Build native module
+        run: npm run build:native:release
+
+      - name: Install
+        run: npm ci
+
+      - name: Package CLI
+        run: npm run dist:cli:mac:arm64
+
+      - name: Zip
+        run: zip -j "dist-cli/bwdc-macos-arm64-$_PACKAGE_VERSION.zip" "dist-cli/macos-arm64/bwdc" "node_modules/dc-native/dc_native.darwin-arm64.node"
+
+      - name: Version Test
+        run: |
+          mkdir -p test/macos-arm64
+          unzip "./dist-cli/bwdc-macos-arm64-$_PACKAGE_VERSION.zip" -d ./test/macos-arm64
+
+          testVersion=$(./test/macos-arm64/bwdc -v)
+
+          echo "version: $_PACKAGE_VERSION"
+          echo "testVersion: $testVersion"
+
+          if [ "$testVersion" != "$_PACKAGE_VERSION" ]; then
+            echo "Version test failed."
+            exit 1
+          fi
+
+      - name: Upload Mac ARM64 Zip to GitHub
+        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
+        with:
+          name: bwdc-macos-arm64-${{ env._PACKAGE_VERSION }}.zip
+          path: ./dist-cli/bwdc-macos-arm64-${{ env._PACKAGE_VERSION }}.zip
+          if-no-files-found: error
+
+
   windows-cli:
     name: Build Windows CLI
     runs-on: windows-2022
@@ -539,6 +602,136 @@ jobs:
           if-no-files-found: error
 
 
+  macos-arm64-gui:
+    name: Build MacOS ARM64 GUI
+    runs-on: macos-15
+    needs: setup
+    if: ${{ needs.setup.outputs.has_secrets == 'true' }}
+    permissions:
+      contents: read
+      id-token: write
+    env:
+      NODE_OPTIONS: --max_old_space_size=4096
+      _PACKAGE_VERSION: ${{ needs.setup.outputs.package_version }}
+      _NODE_VERSION: ${{ needs.setup.outputs.node_version }}
+      HUSKY: 0
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.sha }}
+          persist-credentials: false
+
+      - name: Setup Node Environment
+        uses: ./.github/actions/setup-node-env
+        with:
+          node-version: ${{ env._NODE_VERSION }}
+          platform: macOS
+
+      - name: Set up Rust
+        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
+        with:
+          targets: aarch64-apple-darwin
+
+      - name: Print environment
+        run: |
+          node --version
+          npm --version
+          echo "GitHub ref: $GITHUB_REF"
+          echo "GitHub event: $GITHUB_EVENT"
+
+      - name: Log in to Azure
+        uses: bitwarden/gh-actions/azure-login@main
+        with:
+          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
+          client_id: ${{ secrets.AZURE_CLIENT_ID }}
+
+      - name: Get Azure Key Vault secrets
+        id: get-kv-secrets
+        uses: bitwarden/gh-actions/get-keyvault-secrets@main
+        with:
+          keyvault: gh-directory-connector
+          secrets: "KEYCHAIN-PASSWORD,APP-STORE-CONNECT-AUTH-KEY,APP-STORE-CONNECT-TEAM-ISSUER"
+
+      - name: Get certificates
+        run: |
+          mkdir -p "$HOME/certificates"
+
+          az keyvault secret show --id https://bitwarden-ci.vault.azure.net/certificates/devid-app-cert |
+            jq -r .value | base64 -d > "$HOME/certificates/devid-app-cert.p12"
+
+          az keyvault secret show --id https://bitwarden-ci.vault.azure.net/certificates/devid-installer-cert |
+            jq -r .value | base64 -d > "$HOME/certificates/devid-installer-cert.p12"
+
+          az keyvault secret show --id https://bitwarden-ci.vault.azure.net/certificates/macdev-cert |
+            jq -r .value | base64 -d > "$HOME/certificates/macdev-cert.p12"
+
+      - name: Log out from Azure
+        uses: bitwarden/gh-actions/azure-logout@main
+
+      - name: Set up keychain
+        env:
+          KEYCHAIN_PASSWORD: ${{ steps.get-kv-secrets.outputs.KEYCHAIN-PASSWORD }}
+        run: |
+          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
+          security default-keychain -s build.keychain
+          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
+          security set-keychain-settings -lut 1200 build.keychain
+
+          security import "$HOME/certificates/devid-app-cert.p12" -k build.keychain -P "" \
+            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
+
+          security import "$HOME/certificates/devid-installer-cert.p12" -k build.keychain -P "" \
+            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
+
+          security import "$HOME/certificates/macdev-cert.p12" -k build.keychain -P "" \
+            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
+
+          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
+
+      - name: Install Node dependencies
+        run: npm ci
+
+      - name: Set up private auth key
+        env:
+          _APP_STORE_CONNECT_AUTH_KEY: ${{ steps.get-kv-secrets.outputs.APP-STORE-CONNECT-AUTH-KEY }}
+        run: |
+          mkdir ~/private_keys
+          cat << EOF > ~/private_keys/AuthKey_UFD296548T.p8
+          ${_APP_STORE_CONNECT_AUTH_KEY}
+          EOF
+
+      - name: Build application
+        run: npm run build:dist && npm run clean:dist && electron-builder --mac --arm64 -p never
+        env:
+          APP_STORE_CONNECT_TEAM_ISSUER: ${{ steps.get-kv-secrets.outputs.APP-STORE-CONNECT-TEAM-ISSUER }}
+          APP_STORE_CONNECT_AUTH_KEY: UFD296548T
+          APP_STORE_CONNECT_AUTH_KEY_PATH: ~/private_keys/AuthKey_UFD296548T.p8
+          CSC_FOR_PULL_REQUEST: true
+
+      - name: Upload .zip artifact
+        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
+        with:
+          name: Bitwarden-Connector-${{ env._PACKAGE_VERSION }}-mac-arm64.zip
+          path: ./dist/Bitwarden-Connector-${{ env._PACKAGE_VERSION }}-mac-arm64.zip
+          if-no-files-found: error
+
+      - name: Upload .dmg artifact
+        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
+        with:
+          name: Bitwarden-Connector-${{ env._PACKAGE_VERSION }}-arm64.dmg
+          path: ./dist/Bitwarden-Connector-${{ env._PACKAGE_VERSION }}-arm64.dmg
+          if-no-files-found: error
+
+      - name: Upload .dmg Blockmap artifact
+        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
+        with:
+          name: Bitwarden-Connector-${{ env._PACKAGE_VERSION }}-arm64.dmg.blockmap
+          path: ./dist/Bitwarden-Connector-${{ env._PACKAGE_VERSION }}-arm64.dmg.blockmap
+          if-no-files-found: error
+
+
   check-failures:
     name: Check for failures
     runs-on: ubuntu-24.04
@@ -546,10 +739,12 @@ jobs:
       - setup
       - linux-cli
       - macos-cli
+      - macos-arm64-cli
       - windows-cli
       - windows-gui
       - linux-gui
       - macos-gui
+      - macos-arm64-gui
     permissions:
       id-token: write
     steps:
